function css_beautify(v,h){function a(){return f=v.charAt(++e)}function u(b){for(var l=e;a();)if("\\"==f)a(),a();else if(f==b)break;else if("\n"==f)break;return v.substring(l,e+1)}function w(){for(var f=e;b.test(v.charAt(e+1));)e++;return e!=f}function A(){var f=e;do;while(b.test(a()));return e!=f+1}function k(){var b=e;for(a();a();)if("*"==f&&"/"==v.charAt(e+1)){e++;break}return v.substring(b,e+1)}h=h||{};var D=h.indent_size||4,s=h.indent_char||" ";"string"==typeof D&&(D=parseInt(D));var b=/^\s+$/,
e=-1,f,y=v.match(/^[\r\n]*[\t ]*/)[0],s=Array(D+1).join(s),M=0,z={"{":function(b){z.singleSpace();l.push(b);z.newLine()},"}":function(b){z.newLine();l.push(b);z.newLine()},newLine:function(e){if(!e)for(;b.test(l[l.length-1]);)l.pop();l.length&&l.push("\n");y&&l.push(y)},singleSpace:function(){l.length&&!b.test(l[l.length-1])&&l.push(" ")}},l=[];for(y&&l.push(y);;){var R=A();if(!f)break;"{"==f?(M++,y+=s,z["{"](f)):"}"==f?(M--,y=y.slice(0,-D),z["}"](f)):'"'==f||"'"==f?l.push(u(f)):";"==f?l.push(f,"\n",
y):"/"==f&&"*"==v.charAt(e+1)?(z.newLine(),l.push(k(),"\n",y)):"("==f?"url"==v.substring(e-3,e).toLowerCase()?(l.push(f),w(),a()&&(")"!=f&&'"'!=f&&"'"!=f?l.push(u(")")):e--)):(R&&z.singleSpace(),l.push(f),w()):")"==f?l.push(f):","==f?(w(),l.push(f),z.singleSpace()):("]"!=f&&("["==f||"="==f?w():R&&z.singleSpace()),l.push(f))}return l.join("").replace(/[\n ]+$/,"")}"undefined"!==typeof exports&&(exports.css_beautify=css_beautify);function style_html(v,h){var a,u,w,A,k,D;h=h||{};u=h.indent_size||4;w=h.indent_char||" ";k=h.brace_style||"collapse";A=0==h.max_char?Infinity:h.max_char||250;D=h.unformatted||"a span bdo em strong dfn code samp kbd var cite abbr acronym q sub sup tt i b big small u s strike font ins del pre address dt h1 h2 h3 h4 h5 h6".split(" ");a=new function(){this.pos=0;this.token="";this.current_mode="CONTENT";this.tags={parent:"parent1",parentcount:1,parent1:""};this.token_text=this.last_token=this.last_text=
this.token_type=this.tag_type="";this.Utils={whitespace:["\n","\r","\t"," "],single_token:"br input link meta !doctype basefont base area hr wbr param img isindex ?xml embed ?php ? ?=".split(" "),extra_liners:["head","body","/html"],in_array:function(b,e){for(var f=0;f<e.length;f++)if(b===e[f])return!0;return!1}};this.get_content=function(){for(var b="",e=[],f=!1;"<"!==this.input.charAt(this.pos);){if(this.pos>=this.input.length)return e.length?e.join(""):["","TK_EOF"];b=this.input.charAt(this.pos);
this.pos++;this.line_char_count++;if(this.Utils.in_array(b,this.Utils.whitespace))e.length&&(f=!0),this.line_char_count--;else{if(f){if(this.line_char_count>=this.max_char){e.push("\n");for(f=0;f<this.indent_level;f++)e.push(this.indent_string);this.line_char_count=0}else e.push(" "),this.line_char_count++;f=!1}e.push(b)}}return e.length?e.join(""):""};this.get_contents_to=function(b){if(this.pos==this.input.length)return["","TK_EOF"];var e="";b=RegExp("</"+b+"\\s*>","igm");b.lastIndex=this.pos;b=
(b=b.exec(this.input))?b.index:this.input.length;this.pos<b&&(e=this.input.substring(this.pos,b),this.pos=b);return e};this.record_tag=function(b){this.tags[b+"count"]?this.tags[b+"count"]++:this.tags[b+"count"]=1;this.tags[b+this.tags[b+"count"]]=this.indent_level;this.tags[b+this.tags[b+"count"]+"parent"]=this.tags.parent;this.tags.parent=b+this.tags[b+"count"]};this.retrieve_tag=function(b){if(this.tags[b+"count"]){for(var e=this.tags.parent;e&&b+this.tags[b+"count"]!==e;)e=this.tags[e+"parent"];
e&&(this.indent_level=this.tags[b+this.tags[b+"count"]],this.tags.parent=this.tags[e+"parent"]);delete this.tags[b+this.tags[b+"count"]+"parent"];delete this.tags[b+this.tags[b+"count"]];1==this.tags[b+"count"]?delete this.tags[b+"count"]:this.tags[b+"count"]--}};this.get_tag=function(b){var e="",f=[],a=!1,h;b="undefined"!==typeof b?b:!1;var k=this.pos,l=this.line_char_count;do{if(this.pos>=this.input.length)return b&&(this.pos=k,this.line_char_count=l),f.length?f.join(""):["","TK_EOF"];e=this.input.charAt(this.pos);
this.pos++;this.line_char_count++;if(this.Utils.in_array(e,this.Utils.whitespace))a=!0,this.line_char_count--;else{if("'"===e||'"'===e)if(!f[1]||"!"!==f[1])e+=this.get_unformatted(e),a=!0;"="===e&&(a=!1);f.length&&("="!==f[f.length-1]&&">"!==e&&a)&&(this.line_char_count>=this.max_char?(this.print_newline(!1,f),this.line_char_count=0):(f.push(" "),this.line_char_count++),a=!1);"<"===e&&(h=this.pos-1);f.push(e)}}while(">"!==e);e=f.join("");a=-1!=e.indexOf(" ")?e.indexOf(" "):e.indexOf(">");a=e.substring(1,
a).toLowerCase();"/"===e.charAt(e.length-2)||this.Utils.in_array(a,this.Utils.single_token)?b||(this.tag_type="SINGLE"):"script"===a?b||(this.record_tag(a),this.tag_type="SCRIPT"):"style"===a?b||(this.record_tag(a),this.tag_type="STYLE"):this.is_unformatted(a,D)?(e=this.get_unformatted("</"+a+">",e),f.push(e),0<h&&this.Utils.in_array(this.input.charAt(h-1),this.Utils.whitespace)&&f.splice(0,0,this.input.charAt(h-1)),h=this.pos-1,this.Utils.in_array(this.input.charAt(h+1),this.Utils.whitespace)&&f.push(this.input.charAt(h+
1)),this.tag_type="SINGLE"):"!"===a.charAt(0)?-1!=a.indexOf("[if")?(-1!=e.indexOf("!IE")&&(e=this.get_unformatted("--\x3e",e),f.push(e)),b||(this.tag_type="START")):-1!=a.indexOf("[endif")?(this.tag_type="END",this.unindent()):-1!=a.indexOf("[cdata[")?(e=this.get_unformatted("]]\x3e",e),f.push(e),b||(this.tag_type="SINGLE")):(e=this.get_unformatted("--\x3e",e),f.push(e),this.tag_type="SINGLE"):b||("/"===a.charAt(0)?(this.retrieve_tag(a.substring(1)),this.tag_type="END"):(this.record_tag(a),this.tag_type=
"START"),this.Utils.in_array(a,this.Utils.extra_liners)&&this.print_newline(!0,this.output));b&&(this.pos=k,this.line_char_count=l);return f.join("")};this.get_unformatted=function(b,e){if(e&&-1!=e.toLowerCase().indexOf(b))return"";var a="",h="",k=!0;do{if(this.pos>=this.input.length)break;a=this.input.charAt(this.pos);this.pos++;if(this.Utils.in_array(a,this.Utils.whitespace)){if(!k){this.line_char_count--;continue}if("\n"===a||"\r"===a){h+="\n";this.line_char_count=0;continue}}h+=a;this.line_char_count++;
k=!0}while(-1==h.toLowerCase().indexOf(b));return h};this.get_token=function(){var b;if("TK_TAG_SCRIPT"===this.last_token||"TK_TAG_STYLE"===this.last_token){var a=this.last_token.substr(7);b=this.get_contents_to(a);return"string"!==typeof b?b:[b,"TK_"+a]}if("CONTENT"===this.current_mode)return b=this.get_content(),"string"!==typeof b?b:[b,"TK_CONTENT"];if("TAG"===this.current_mode)return b=this.get_tag(),"string"!==typeof b?b:[b,"TK_TAG_"+this.tag_type]};this.get_full_indent=function(b){b=this.indent_level+
b||0;return 1>b?"":Array(b+1).join(this.indent_string)};this.is_unformatted=function(b,a){if(!this.Utils.in_array(b,a))return!1;if("a"!==b.toLowerCase()||!this.Utils.in_array("a",a))return!0;var f=this.get_tag(!0);return f&&this.Utils.in_array(f,a)?!0:!1};this.printer=function(a,e,f,h,k){this.input=a||"";this.output=[];this.indent_character=e;this.indent_string="";this.indent_size=f;this.brace_style=k;this.indent_level=0;this.max_char=h;for(a=this.line_char_count=0;a<this.indent_size;a++)this.indent_string+=
this.indent_character;this.print_newline=function(a,b){this.line_char_count=0;if(b&&b.length){if(!a)for(;this.Utils.in_array(b[b.length-1],this.Utils.whitespace);)b.pop();b.push("\n");for(var e=0;e<this.indent_level;e++)b.push(this.indent_string)}};this.print_token=function(a){this.output.push(a)};this.indent=function(){this.indent_level++};this.unindent=function(){0<this.indent_level&&this.indent_level--}};return this};for(a.printer(v,w,u,A,k);;){u=a.get_token();a.token_text=u[0];a.token_type=u[1];
if("TK_EOF"===a.token_type)break;switch(a.token_type){case "TK_TAG_START":a.print_newline(!1,a.output);a.print_token(a.token_text);a.indent();a.current_mode="CONTENT";break;case "TK_TAG_STYLE":case "TK_TAG_SCRIPT":a.print_newline(!1,a.output);a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_TAG_END":"TK_CONTENT"===a.last_token&&""===a.last_text&&(u=a.token_text.match(/\w+/)[0],w=a.output[a.output.length-1].match(/<\s*(\w+)/),(null===w||w[1]!==u)&&a.print_newline(!0,a.output));a.print_token(a.token_text);
a.current_mode="CONTENT";break;case "TK_TAG_SINGLE":u=a.token_text.match(/^\s*<([a-z]+)/i);(!u||!a.Utils.in_array(u[1],D))&&a.print_newline(!1,a.output);a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_CONTENT":""!==a.token_text&&a.print_token(a.token_text);a.current_mode="TAG";break;case "TK_STYLE":case "TK_SCRIPT":if(""!==a.token_text){a.output.push("\n");u=a.token_text;if("TK_SCRIPT"==a.token_type)var s="function"==typeof js_beautify&&js_beautify;else"TK_STYLE"==a.token_type&&
(s="function"==typeof css_beautify&&css_beautify);A="keep"==h.indent_scripts?0:"separate"==h.indent_scripts?-a.indent_level:1;w=a.get_full_indent(A);s?u=s(u.replace(/^\s*/,w),h):(k=u.match(/^\s*/)[0].match(/[^\n\r]*$/)[0].split(a.indent_string).length-1,A=a.get_full_indent(A-k),u=u.replace(/^\s*/,w).replace(/\r\n|\r|\n/g,"\n"+A).replace(/\s*$/,""));u&&(a.print_token(u),a.print_newline(!0,a.output))}a.current_mode="TAG"}a.last_token=a.token_type;a.last_text=a.token_text}return a.output.join("")}
"undefined"!==typeof exports&&(exports.html_beautify=style_html);function js_beautify(v,h){return(new Beautifier(v,h)).beautify()}
function Beautifier(v,h){function a(d){for(d="undefined"===typeof d?!1:d;r.length&&(" "===r[r.length-1]||r[r.length-1]===G||r[r.length-1]===N||d&&("\n"===r[r.length-1]||"\r"===r[r.length-1]));)r.pop()}function u(d){return d.replace(/^\s\s*|\s\s*$/,"")}function w(){return r.length&&"\n"===r[r.length-1]}function A(d){d="undefined"===typeof d?!1:d;if(Z&&!d){var a="",a=0;a:{a=r.length-1;0>a&&(a+=r.length);a>r.length-1&&(a=r.length-1);for(a++;0<a--;)if(a in r&&"\n"===r[a])break a;a=-1}a+=1;a<r.length&&
(a=r.slice(a).join(""),a=a.length+t.length+(p?1:0),a>=Z&&(d=!0))}if((S&&H||d)&&!w())k(!1,!0),O=!0,H=!1}function k(d,a){p=O=!1;if(!a&&";"!==n)for(;"STATEMENT"===c.mode&&!c.if_block;)y();r.length&&(d||!w())&&r.push("\n")}function D(d){void 0===d?d=1:"number"!==typeof d&&(d=d?1:0);if(""!=n)for(var a=0;a<d;a+=1)r.push(G)}function s(d){d=d||t;w()&&(F&&e(c.mode)&&I.length?r.push(I.join("")+""):(N&&r.push(N),D(c.indentation_level),D(c.var_line&&c.var_line_reindented),D(O)));O=!1;if(p&&r.length){var a=r[r.length-
1];!w()&&(" "!==a&&a!==G)&&r.push(" ")}p=!1;r.push(d)}function b(d){c&&T.push(c);c={previous_mode:c?c.mode:"BLOCK",mode:d,var_line:!1,var_line_tainted:!1,var_line_reindented:!1,in_html_comment:!1,if_block:!1,do_block:!1,do_while:!1,in_case_statement:!1,in_case:!1,case_body:!1,indentation_level:c?c.indentation_level+(c.var_line&&c.var_line_reindented?1:0):0,ternary_depth:0}}function e(d){return"[EXPRESSION]"===d||"[INDENTED-EXPRESSION]"===d}function f(d){return l(d,["[EXPRESSION]","(EXPRESSION)","(FOR-EXPRESSION)",
"(COND-EXPRESSION)"])}function y(){if(0<T.length){var d=c.mode;c=T.pop();c.previous_mode=d}}function M(){return"do"===n||"else"===n&&"if"!==t||"TK_END_EXPR"===m&&("(FOR-EXPRESSION)"===c.previous_mode||"(COND-EXPRESSION)"===c.previous_mode)?(A(),b("STATEMENT"),c.indentation_level+=1,O=!1,!0):!1}function z(d){return l(d,"case return do if throw else".split(" "))}function l(d,a){for(var c=0;c<a.length;c+=1)if(a[c]===d)return!0;return!1}function R(d){for(var a=g,c=q.charAt(a);l(c,V)&&c!==d;){a++;if(a>=
x)return!1;c=q.charAt(a)}return c===d}function Y(){B=0;if(g>=x)return["","TK_EOF"];H=!1;I=[];var d=q.charAt(g);for(g+=1;l(d,V);){"\n"===d?(B+=1,I=[]):B&&(d===G?I.push(G):"\r"!==d&&I.push(" "));if(g>=x)return["","TK_EOF"];d=q.charAt(g);g+=1}if(l(d,U)){if(g<x)for(;l(q.charAt(g),U)&&!(d+=q.charAt(g),g+=1,g===x););if(g!==x&&d.match(/^[0-9]+[Ee]$/)&&("-"===q.charAt(g)||"+"===q.charAt(g))){var a=q.charAt(g);g+=1;var b=Y(),d=d+(a+b[0]);return[d,"TK_WORD"]}return"in"===d?[d,"TK_OPERATOR"]:[d,"TK_WORD"]}if("("===
d||"["===d)return[d,"TK_START_EXPR"];if(")"===d||"]"===d)return[d,"TK_END_EXPR"];if("{"===d)return[d,"TK_START_BLOCK"];if("}"===d)return[d,"TK_END_BLOCK"];if(";"===d)return[d,"TK_SEMICOLON"];if("/"===d){a="";b=!0;if("*"===q.charAt(g)){g+=1;if(g<x)for(;g<x&&!("*"===q.charAt(g)&&q.charAt(g+1)&&"/"===q.charAt(g+1));){d=q.charAt(g);a+=d;if("\n"===d||"\r"===d)b=!1;g+=1;if(g>=x)break}g+=2;return b&&0===B?["/*"+a+"*/","TK_INLINE_COMMENT"]:["/*"+a+"*/","TK_BLOCK_COMMENT"]}if("/"===q.charAt(g)){for(a=d;"\r"!==
q.charAt(g)&&"\n"!==q.charAt(g)&&!(a+=q.charAt(g),g+=1,g>=x););return[a,"TK_COMMENT"]}}if("'"===d||'"'===d||"/"===d&&("TK_WORD"===m&&z(n)||"TK_END_EXPR"==m&&l(c.previous_mode,["(COND-EXPRESSION)","(FOR-EXPRESSION)"])||l(m,"TK_COMMENT TK_START_EXPR TK_START_BLOCK TK_END_BLOCK TK_OPERATOR TK_EQUALS TK_EOF TK_SEMICOLON TK_COMMA".split(" ")))){var a=d,e=b=!1,f=d;if(g<x)if("/"===a)for(d=!1;b||d||q.charAt(g)!==a;){if(f+=q.charAt(g),b?b=!1:(b="\\"===q.charAt(g),"["===q.charAt(g)?d=!0:"]"===q.charAt(g)&&
(d=!1)),g+=1,g>=x)return[f,"TK_STRING"]}else for(;b||q.charAt(g)!==a;){f+=q.charAt(g);if(b){if("x"===q.charAt(g)||"u"===q.charAt(g))e=!0;b=!1}else b="\\"===q.charAt(g);g+=1;if(g>=x)return[f,"TK_STRING"]}g+=1;f+=a;if(e&&ba)a:{for(var d=f,b=!1,e="",f=0,h="",k=0,p;b||f<d.length;)if(p=d.charAt(f),f++,b){b=!1;if("x"===p)h=d.substr(f,2),f+=2;else if("u"===p)h=d.substr(f,4),f+=4;else{e+="\\"+p;continue}if(!h.match(/^[0123456789abcdefABCDEF]+$/)){f=d;break a}k=parseInt(h,16);if(0<=k&&32>k)e="x"===p?e+("\\x"+
h):e+("\\u"+h);else if(34==k||39===k||92==k)e+="\\"+String.fromCharCode(k);else if("x"===p&&126<k&&255>=k){f=d;break a}else e+=String.fromCharCode(k)}else"\\"==p?b=!0:e+=p;f=e}if("/"===a)for(;g<x&&l(q.charAt(g),U);)f+=q.charAt(g),g+=1;return[f,"TK_STRING"]}if("#"===d){if(0===r.length&&"!"===q.charAt(g)){for(f=d;g<x&&"\n"!==d;)d=q.charAt(g),f+=d,g+=1;return[u(f)+"\n","TK_UNKNOWN"]}a="#";if(g<x&&l(q.charAt(g),$)){do d=q.charAt(g),a+=d,g+=1;while(g<x&&"#"!==d&&"="!==d);"#"!==d&&("["===q.charAt(g)&&"]"===
q.charAt(g+1)?(a+="[]",g+=2):"{"===q.charAt(g)&&"}"===q.charAt(g+1)&&(a+="{}",g+=2));return[a,"TK_WORD"]}}if("<"===d&&"\x3c!--"===q.substring(g-1,g+3)){g+=3;for(d="\x3c!--";"\n"!==q.charAt(g)&&g<x;)d+=q.charAt(g),g++;c.in_html_comment=!0;return[d,"TK_COMMENT"]}if("-"===d&&c.in_html_comment&&"--\x3e"===q.substring(g-1,g+2))return c.in_html_comment=!1,g+=2,["--\x3e","TK_COMMENT"];if("."===d)return[d,"TK_DOT"];if(l(d,J)){for(;g<x&&l(d+q.charAt(g),J)&&!(d+=q.charAt(g),g+=1,g>=x););return","===d?[d,"TK_COMMA"]:
"="===d?[d,"TK_EQUALS"]:[d,"TK_OPERATOR"]}return[d,"TK_UNKNOWN"]}function aa(){M();if("["===t){if("TK_WORD"===m||")"===n){l(n,K)&&(p=!0);b("(EXPRESSION)");s();return}"[EXPRESSION]"===c.mode||"[INDENTED-EXPRESSION]"===c.mode?"]"===P&&","===n?("[EXPRESSION]"===c.mode&&(c.mode="[INDENTED-EXPRESSION]",F||(c.indentation_level+=1)),b("[EXPRESSION]"),F||k()):"["===n?("[EXPRESSION]"===c.mode&&(c.mode="[INDENTED-EXPRESSION]",F||(c.indentation_level+=1)),b("[EXPRESSION]"),F||k()):b("[EXPRESSION]"):b("[EXPRESSION]")}else"for"===
n?b("(FOR-EXPRESSION)"):l(n,["if","while"])?b("(COND-EXPRESSION)"):b("(EXPRESSION)");if(";"===n||"TK_START_BLOCK"===m)k();else if("TK_END_EXPR"===m||"TK_START_EXPR"===m||"TK_END_BLOCK"===m||"."===n)H&&k();else if("TK_WORD"!==m&&"TK_OPERATOR"!==m)p=!0;else if("function"===Q||"typeof"===Q)ca&&(p=!0);else if(l(n,K)||"catch"===n)da&&(p=!0);"("===t&&("TK_EQUALS"===m||"TK_OPERATOR"===m)&&"OBJECT"!==c.mode&&A();s()}function ea(){"]"===t&&!F&&"[INDENTED-EXPRESSION]"===c.mode&&"]"===n?(y(),k(),s()):(y(),s(),
c.do_while&&"(COND-EXPRESSION)"===c.previous_mode&&(c.previous_mode="(EXPRESSION)",c.do_block=!1,c.do_while=!1))}function fa(){b("BLOCK");var a=R("}");"expand-strict"===C?a||k():"expand"===C?"TK_OPERATOR"!==m&&("TK_EQUALS"===m||z(n)&&"else"!==n?p=!0:k()):"TK_OPERATOR"!==m&&"TK_START_EXPR"!==m?"TK_START_BLOCK"===m?k():p=!0:e(c.previous_mode)&&","===n&&("}"===P?p=!0:k());s();c.indentation_level+=1}function ga(){y();"expand"===C||"expand-strict"===C?"{"!==n&&k():"TK_START_BLOCK"!==m&&(e(c.mode)&&F?(F=
!1,k(),F=!0):k());s()}function ha(){M()||H&&("TK_OPERATOR"!==m&&"TK_EQUALS"!==m&&(S||"var"!==n))&&k();if(c.do_block&&!c.do_while){if("while"===t){p=!0;s();p=!0;c.do_while=!0;return}k();c.do_block=!1}if(c.if_block&&"else"!==t){for(;"STATEMENT"===c.mode;)y();c.if_block=!1}if("function"===t){c.var_line&&"TK_EQUALS"!==m&&(c.var_line_reindented=!0);if((w()||";"===n)&&"{"!==n&&"TK_BLOCK_COMMENT"!==m&&"TK_COMMENT"!==m){B=w()?B:0;S||(B=1);for(var d=0;d<2-B;d++)k(!0)}"TK_WORD"===m?"get"===n||"set"===n||"new"===
n||"return"===n?p=!0:k():"TK_OPERATOR"===m||"="===n?p=!0:f(c.mode)||k();s();Q=t}else if("case"===t||"default"===t&&c.in_case_statement)k(),c.case_body&&(c.indentation_level--,c.case_body=!1),s(),c.in_case=!0,c.in_case_statement=!0;else{E="NONE";"TK_END_BLOCK"===m?l(t,["else","catch","finally"])?"expand"===C||"end-expand"===C||"expand-strict"===C?E="NEWLINE":(E="SPACE",p=!0):E="NEWLINE":"TK_SEMICOLON"===m&&"BLOCK"===c.mode?E="NEWLINE":"TK_SEMICOLON"===m&&f(c.mode)?E="SPACE":"TK_STRING"===m?E="NEWLINE":
"TK_WORD"===m?E="SPACE":"TK_START_BLOCK"===m?E="NEWLINE":"TK_END_EXPR"===m&&(p=!0,E="NEWLINE");l(t,K)&&")"!==n&&(E="else"===n?"SPACE":"NEWLINE");("TK_COMMA"===m||"TK_START_EXPR"===m||"TK_EQUALS"===m||"TK_OPERATOR"===m)&&"OBJECT"!==c.mode&&A();if(l(t,["else","catch","finally"]))"TK_END_BLOCK"!==m||"expand"===C||"end-expand"===C||"expand-strict"===C?k():(a(!0),p=!0);else if("NEWLINE"===E)if(z(n))p=!0;else if("TK_END_EXPR"!==m){if(("TK_START_EXPR"!==m||"var"!==t)&&":"!==n)"if"===t&&"else"===Q&&"{"!==
n?p=!0:(c.var_line=!1,c.var_line_reindented=!1,k())}else l(t,K)&&")"!==n&&(c.var_line=!1,c.var_line_reindented=!1,k());else e(c.mode)&&","===n&&"}"===P?k():"SPACE"===E&&(p=!0);s();Q=t;"var"===t&&(c.var_line=!0,c.var_line_reindented=!1,c.var_line_tainted=!1);"do"===t&&(c.do_block=!0);"if"===t&&(c.if_block=!0)}}function ia(){for(;"STATEMENT"===c.mode&&!c.if_block;)y();s();c.var_line=!1;c.var_line_reindented=!1;"OBJECT"===c.mode&&(c.mode="BLOCK")}function ja(){M()?p=!0:"TK_WORD"===m?p=!0:"TK_COMMA"===
m||"TK_START_EXPR"===m||"TK_EQUALS"===m||"TK_OPERATOR"===m?"OBJECT"!==c.mode&&A():k();s()}function ka(){c.var_line&&(c.var_line_tainted=!0);p=!0;s();p=!0}function la(){if(c.var_line){if(f(c.mode)||"TK_END_BLOCK"===m)c.var_line_tainted=!1;c.var_line&&(c.var_line_reindented=!0);s();c.var_line_tainted?(c.var_line_tainted=!1,k()):p=!0}else"TK_END_BLOCK"===m&&"(EXPRESSION)"!==c.mode?(s(),"OBJECT"===c.mode&&"}"===n?k():p=!0):"OBJECT"===c.mode?(s(),k()):(s(),p=!0)}function ma(){var a=!0,b=!0;z(n)?(p=!0,
s()):"*"===t&&"TK_DOT"===m&&!P.match(/^\d+$/)?s():":"===t&&c.in_case?(c.case_body=!0,c.indentation_level+=1,s(),k(),c.in_case=!1):"::"===t?s():(l(t,["--","++","!"])||l(t,["-","+"])&&(l(m,["TK_START_BLOCK","TK_START_EXPR","TK_EQUALS","TK_OPERATOR"])||l(n,K)||","==n)?(b=a=!1,";"===n&&f(c.mode)&&(a=!0),"TK_WORD"===m&&l(n,K)&&(a=!0),("BLOCK"===c.mode||"STATEMENT"===c.mode)&&("{"===n||";"===n)&&k()):":"===t?0===c.ternary_depth?("BLOCK"===c.mode&&(c.mode="OBJECT"),a=!1):c.ternary_depth-=1:"?"===t&&(c.ternary_depth+=
1),p=p||a,s(),p=b)}function na(){for(var a=t,a=a.replace(/\x0d/g,""),b=[],c=a.indexOf("\n");-1!==c;)b.push(a.substring(0,c)),a=a.substring(c+1),c=a.indexOf("\n");a.length&&b.push(a);a:{a=b.slice(1);for(c=0;c<a.length;c++)if("*"!==u(a[c]).charAt(0)){a=!1;break a}a=!0}if(a){k(!1,!0);s(b[0]);for(a=1;a<b.length;a++)k(!1,!0),s(" "+u(b[a]))}else{1<b.length?k(!1,!0):"TK_END_BLOCK"===m?k(!1,!0):p=!0;s(b[0]);r.push("\n");for(a=1;a<b.length;a++)r.push(b[a]),r.push("\n")}R("\n")||k(!1,!0)}function oa(){p=!0;
s();p=!0}function pa(){H&&k(!1,!0);","===n&&!H&&a(!0);p=!0;s();k(!1,!0)}function qa(){z(n)?p=!0:A(")"===n&&ra);s()}function sa(){s();"\n"===t[t.length-1]&&k()}var q,r,t,m,n,P,Q,c,T,G,V,U,J,g,K,$,E,L,H,B,O,p,I,N="";h=h?h:{};var C;void 0!==h.space_after_anon_function&&void 0===h.jslint_happy&&(h.jslint_happy=h.space_after_anon_function);void 0!==h.braces_on_own_line&&(C=h.braces_on_own_line?"expand":"collapse");C=h.brace_style?h.brace_style:C?C:"collapse";var W=h.indent_size?parseInt(h.indent_size):
4,ta=h.indent_char?h.indent_char:" ",S="undefined"===typeof h.preserve_newlines?!0:h.preserve_newlines,ra="undefined"===typeof h.break_chained_methods?!1:h.break_chained_methods,X="undefined"===typeof h.max_preserve_newlines?0:parseInt(h.max_preserve_newlines),ca="undefined"===h.jslint_happy?!0:h.jslint_happy,F="undefined"===typeof h.keep_array_indentation?!1:h.keep_array_indentation,da="undefined"===typeof h.space_before_conditional?!0:h.space_before_conditional,ba="undefined"===typeof h.unescape_strings?
!1:h.unescape_strings,Z="undefined"===typeof h.wrap_line_length?0:parseInt(h.wrap_line_length),x=v.length;for(G="";0<W;)G+=ta,W-=1;for(;v&&(" "===v.charAt(0)||"\t"===v.charAt(0));)N+=v.charAt(0),v=v.substring(1);q=v;Q="";m="TK_START_EXPR";P=n="";r=[];p=O=!1;I=[];V=["\n","\r","\t"," "];U="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_$".split("");$="0123456789".split("");J="+ - * / % & ++ -- = += -= *= /= %= == === != !== > < >= <= >> << >>> >>>= >>= <<= && &= | || ! !! , : ? ^ ^= |= ::";
J+=" <%= <% %> <?= <? ?>";J=J.split(" ");K="continue try throw return var if switch case default for while break function".split(" ");T=[];b("BLOCK");g=0;this.beautify=function(){for(var a={TK_START_EXPR:aa,TK_END_EXPR:ea,TK_START_BLOCK:fa,TK_END_BLOCK:ga,TK_WORD:ha,TK_SEMICOLON:ia,TK_STRING:ja,TK_EQUALS:ka,TK_OPERATOR:ma,TK_COMMA:la,TK_BLOCK_COMMENT:na,TK_INLINE_COMMENT:oa,TK_COMMENT:pa,TK_DOT:qa,TK_UNKNOWN:sa};;){var b=Y();t=b[0];L=b[1];if("TK_EOF"===L)break;if(F&&e(c.mode))for(i=0;i<B;i+=1)k(!0);
else if(H=0<B,X&&B>X&&(B=X),S&&1<B){k();for(i=1;i<B;i+=1)k(!0)}a[L]();"TK_INLINE_COMMENT"!==L&&("TK_COMMENT"!==L&&"TK_UNKNOWN"!==L)&&(P=n,m=L,n=t)}return N+r.join("").replace(/[\r\n ]+$/,"")}}"undefined"!==typeof exports&&(exports.js_beautify=js_beautify);
